### PR TITLE
Sync the spec (2021.02.26)

### PR DESCRIPTION
**Pull request by displague**
* [x] The latest spec sync has taken in all of the patches from this project.
* [x] The Makefile is updated to handle the case when there are no patches.
* [x] The client and types are regenerated
* [x] The examples still work (Demonstrates pagination #6)

### CODE REVIEW

**Comment by displague** [comment]
I'm not sure if 
731635d is necessary.  `replace "github.com/t0mk/gometal" => ../..` may be the default behavior for a `module` in a subdirectory.

**Comment by t0mk** [comment]
>  replace "github.com/t0mk/gometal" => ../.. may be the default behavior for a module in a subdirectory.

Did you add the replace because the examples wouldn't build in your fork?

From my point of view it works either way. If anyone would copy the example out, she would probably adapt its go.mod.

**Comment by t0mk** [comment]
@displague thanks for the PR. Looks good. I verified that the examples build, and that `$ make` will not taint git index.

Good job having EM API devs updating the api-doc json. 

Feel free to merge.

**Comment by displague** [comment]
I'm more concerned with `main.go` being copy/paste ready than `go.mod`, but I agree the whole directory should be reusable, but the examples should work in the commit.  Maybe we can say something about that in the README about examples.

**Pull request merged**
