### PR TITLE
device requests must state the default for  ip_addresses.public

### PR DESCRIPTION
**Pull request by displague**
define truthy default explicitly for ip_addresses public field in device create request

    Without this definition, `public: false` is never sent to the API.

### CODE REVIEW

**Comment by t0mk** [comment]
@displague looks good, examples run, but can you please explain where's the `type ClientOption` is coming from?

**Comment by displague** [comment]
`ClientOption` came from updating the go-swagger image to `latest`.

I have another branch or commit that I will include in a PR that forces a `docker pull` so we always build with latest.

**Comment by displague** [comment]
GitHub is hiding the generated files in the results, the files it shows by default are the ones that I modified by hand.
I  split my commits up so that the generated changes are in their own commit.

**Comment by t0mk** [comment]
@displague thanks.

**Pull request merged**
