### PR TITLE
api: updated with latest swagger, including get ports by id

### PR DESCRIPTION
**Pull request by displague**
Adds only the changes from the latest equinix-metal.swagger.json, focused on changes in support of the hybrid-bonded port configurations.
* FindPortByID added (`GET /ports/{id}`)
* `/ports/{id}/assign` now returns added Port property `disbond_operation_supported: bool`

Signed-off-by: Marques Johansson <mjohansson@equinix.com>

### CODE REVIEW

**Comment by t0mk** [comment]
@displague thanks for the PR. I see you updated the swagger api json. Will running gen.sh rewrite the api json? If yes, updating `equinix-metal.swagger.json` is pointless, isn't it? Maybe we could have 2 scripts - download_and_gen.sh and gen.sh. The latter one would use the swagger json from the repo without downloading it.

**Comment by displague** [comment]
I disabled the download and patch to generate a smaller diff for the 0.26 PR and then updated the spec to cherry-pick these port related changes.

**Comment by displague** [comment]
It does seem helpful to split the download and patch functionality from the generator. Maybe we make these two Makefile tasks.

**Comment by t0mk** [comment]
@displague when I run the examples from code checked out from this PR, it didn't compile because of some iisue in the ports code. I had to run the swagger generating, and with the commit I pushed, the examples run.

bafe047 looks good? If yes, I merge.

**Comment by displague** [comment]
@t0mk feel free to merge.

What I notice is that when you run the swagger command, we get these empty `var ()` blocks. I suspect we are running different versions of go-swagger, which is what #9 tried to address 🙁 .

**Comment by t0mk** [comment]
@displague you're right, sorry. I rebased this on current main (where there's swagger-gen from docker) and verified that `make gen` didn't change the sources, and the examples run. I retracted my last commit and I'm merging.

**Pull request merged**
